name: CD - Deploy to Minikube

on:
  
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Minikube
    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4
        
      -  name: 0. List files in the repository
         run: |
          echo "Current directory: $(pwd)"
          echo "Listing all files..."
          ls -R
          
      - name: 2. Set up and Start Minikube
        uses: medyagh/setup-minikube@latest
      - name: 4. Update Deployment with new Image Tag
        run: |
          sed -i "s|__IMAGE_NAME__|${{ env.DOCKER_IMAGE }}:${{ github.sha }}|g" k8s/deployment.yaml
          echo "--- Updated deployment.yaml ---"
          cat k8s/deployment.yaml

      - name: 3. Deploy Application to Minikube
        run: |
          echo "Applying Kubernetes manifests..."
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      - name: 4. Verify Deployment
        run: |
          echo "Waiting for deployment to be ready..."
          kubectl rollout status deployment/my-ml-app-deployment --timeout=120s

          echo -e "\n\n--- Deployment Status ---"
          kubectl get deployment

          echo -e "\n\n--- Pod Status ---"
          kubectl get pods

          echo -e "\n\n--- Service Status ---"
          kubectl get service

          echo -e "\n\nDeployment to Minikube successful!"
